# Generated by Django 4.0.6 on 2022-10-09 16:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_whislist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whislist',
            new_name='Wishlist',
        ),
    ]
