# Generated by Django 4.0.6 on 2022-10-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_fname_order_fnames_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fnames',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
